### ISSUE TITLE
4x4 Matrix Issue

### ISSUE THREAD

**Issue by mcjka** [Guitarman9119/Raspberry-Pi-Pico-#5]
I copy pasted your code, and I almost got there! Here is the errors:

Please enter a key from the keypad

*not in the error, but i pressed a key, no output, then decide to stop the program*

Traceback (most recent call last):
  File "<stdin>", line 47, in <module>
  File "<stdin>", line 42, in scankeys
KeyboardInterrupt: 

I tried moving the wires to the other side of it. Right now it is to the right of the Pico, and when I tried to the left, it gave me the same error. Is there an orientation it needs to be in, and, how do I fix this? Is this a bug in the code? Using Ubuntu 22.04 on a old Lenovo

**Comment by mcjka** [comment]
Ok, I have tinkered with it more, and I put it on the left side of the pico. I forgot to put it all the way next to the gpio pins. I tried doing it on the right, but it would spit errors whenever i pressed a letter (not number). I put it on the left, and it still does not seem to work. No output. When I stop it, though, it gives the same error. The first error was not fully copied, it was "line 47, in <module>
